CREATE TABLE KHACH_HANG(
    ID INT NOT NULL PRIMARY KEY,
    SO_DIEN_THOAI VARCHAR(15),
    NGAY_THAM_GIA DATE,
    TEN VARCHAR(50)
);


CREATE TABLE DIA_CHI_KHACH_HANG(
    ID INT NOT NULL PRIMARY KEY,
    DIA_CHI VARCHAR(50),
    MAC_DINH VARCHAR(50)
);

CREATE TABLE DIA_CHI_GIAO_HANG(
    ID_DC NUMBER NOT NULL,
    ID_KH NUMBER NOT NULL
);

ALTER TABLE DIA_CHI_GIAO_HANG ADD CONSTRAINT PK_DCKH PRIMARY KEY (ID_DC,ID_KH);

CREATE TABLE DON_HANG(
    ID INT NOT NULL PRIMARY KEY,
    ID_KH INT,
    ID_KM INT,
    ID_DIA_CHI INT,
    ID_THU_NGAN INT,
    TONG_TIEN INT,
    SO_BAN_TAO_DON INT,
    HINH_THUC_THANH_TOAN INT,
    TRANG_THAI VARCHAR(50),
    DAT_ONLINE INT,
    NGAY_DAT DATE,
    GHI_CHU VARCHAR(100)
);

CREATE TABLE CHUONG_TRINH_KM(
    ID INT NOT NULL PRIMARY KEY,
    MO_TA VARCHAR(50),
    NGAY_BAT_DAU DATE,
    NGAY_KET_THUC DATE,
    MA_GIAM_GIA INT
    PHAN_TRAM_GIAM_GIA INT
);

CREATE TABLE KM_DON_HANG(
    ID_DON INT NOT NULL,
    ID_KM INT NOT NULL,
);

ALTER TABLE KM_DON_HANG ADD CONSTRAINT PK_DISC PRIMARY KEY (ID_DON,ID_KM);

CREATE TABLE MON_AN(
    ID INT NOT NULL PRIMARY KEY,
    TEN_MON VARCHAR(50),
    MO_TA VARCHAR(50),
    LOAI VARCHAR(50),	
    HINH_ANH BLOB
);



CREATE TABLE CHITIET_DON(
ID_DON NUMBER NOT NULL,
ID_MON NUMBER NOT NULL,
SOLUONG NUMBER
);
ALTER TABLE CHITIET_DON ADD CONSTRAINT PK_DM PRIMARY KEY (ID_DON,ID_MON);
ALTER TABLE CHITIET_DON ADD CONSTRAINT FK_DM FOREIGN KEY(ID_MON) REFERENCES MON_AN(ID);
ALTER TABLE CHITIET_DON ADD CONSTRAINT FK_DH FOREIGN KEY (ID_DON) REFERENCES DON_HANG(ID);

CREATE TABLE NGUYEN_LIEU(
    ID INT NOT NULL PRIMARY KEY,
    TEN VARCHAR(50),
    DON_VI VARCHAR(20),
    SO_LUONG_TRONG_KHO INT
);

CREATE TABLE NGUYEN_LIEU_MON_AN(
    ID_NL INT NOT NULL,
    ID_MON INT NOT NULL,
    SO_LUONG INT
);

ALTER TABLE NGUYEN_LIEU_MON_AN ADD CONSTRAINT PK_NLMA PRIMARY KEY (ID_NL,ID_MON);

CREATE TABLE NHA_CUNG_CAP(
    ID INT NOT NULL PRIMARY KEY,
    TEN VARCHAR(50),
    SO_DIEN_THOAI VARCHAR(15),
    EMAIL VARCHAR(50),
    DIA_CHI VARCHAR(50)
);

CREATE TABLE NHAN_VIEN(
    ID INT NOT NULL PRIMARY KEY,
    TEN VARCHAR(50),
    DON_VI VARCHAR(50),
    SO_DIEN_THOAI VARCHAR(15),
    CHUC_VU VARCHAR(50),
    ID_QUAN_LY INT
);


CREATE TABLE NHACUNGCAP_NGUYENLIEU_QUANLY_BEP(
    ID_NL INT NOT NULL,
    ID_NCC INT NOT NULL,
    ID_QUAN_LY INT NOT NULL,
    ID_BEP INT NOT NULL
);

ALTER TABLE NHACUNGCAP_NGUYENLIEU_QUANLY_BEP ADD CONSTRAINT PK_NCCNLQLB PRIMARY KEY (ID_NL,ID_NCC,ID_QUAN_LY,ID_BEP);



--khoa ngoai    
--bang DIA_CHI_GIAO_HANG
ALTER TABLE DIA_CHI_GIAO_HANG ADD CONSTRAINT FK_DIA_CHI_GIAO_HANG__HANG 
    FOREIGN KEY (ID_KH) REFERENCES KHACH_HANG(ID);
ALTER TABLE DIA_CHI_GIAO_HANG ADD CONSTRAINT FK_DIA_CHI_KHACH_HANG_DIA_CHI_GIAO_HANG 
    FOREIGN KEY (ID_DC) REFERENCES  DIA_CHI_KHACH_HANG(ID);
--bang don hang
ALTER TABLE DON_HANG ADD CONSTRAINT FK_DON_HANG_KHACH_HANG 
    FOREIGN KEY (ID_KH) REFERENCES KHACH_HANG(ID);

ALTER TABLE DON_HANG ADD CONSTRAINT FK_DON_HANG_CHUONG_TRINH_KM 
    FOREIGN KEY (ID_KM) REFERENCES CHUONG_TRINH_KM(ID);

ALTER TABLE DON_HANG ADD CONSTRAINT FK_DON_HANG_DIA_CHI_GIAO_HANG 
    FOREIGN KEY (ID_DIA_CHI) REFERENCES DIA_CHI_KHACH_HANG(ID);

    ALTER TABLE DON_HANG ADD CONSTRAINT FK_DON_HANG_NHAN_VIEN_THU_NGAN 
    FOREIGN KEY (ID_THU_NGAN) REFERENCES NHAN_VIEN(ID);


--bang KM_DON_HANG

ALTER TABLE KM_DON_HANG ADD CONSTRAINT FK_DISCOUNT_DON_HANG 
    FOREIGN KEY (ID_DON) REFERENCES DON_HANG(ID);

ALTER TABLE KM_DON_HANG ADD CONSTRAINT FK_DISCOUNT_CHUONG_TRINH_KM 
    FOREIGN KEY (ID_KM) REFERENCES CHUONG_TRINH_KM(ID);




--bang Nguyen lieu mon an
ALTER TABLE NGUYEN_LIEU_MON_AN
ADD CONSTRAINT FK_NLMA_NL FOREIGN KEY (ID_NL)
REFERENCES NGUYEN_LIEU(ID);

ALTER TABLE NGUYEN_LIEU_MON_AN
ADD CONSTRAINT FK_NLMA_MON FOREIGN KEY (ID_MON)
REFERENCES MON_AN(ID);

-- bang nha cung cap nguyen lieu
ALTER TABLE NHACUNGCAP_NGUYENLIEU_QUANLY_BEP
ADD CONSTRAINT FK_NL_NCC
FOREIGN KEY (ID_NL)
REFERENCES NGUYEN_LIEU(ID);

ALTER TABLE NHACUNGCAP_NGUYENLIEU_QUANLY_BEP
ADD CONSTRAINT FK_NL_QUANLY
FOREIGN KEY (ID_QUAN_LY)
REFERENCES NHAN_VIEN(ID);

ALTER TABLE NHACUNGCAP_NGUYENLIEU_QUANLY_BEP
ADD CONSTRAINT FK_NCC
FOREIGN KEY (ID_NCC)
REFERENCES NHA_CUNG_CAP(ID);


