-- CREATE or replace DIRECTORY DIRECT_OF_IMAGE AS 'D:\LIST_MENU\food';

CREATE OR REPLACE PROCEDURE THEM_MON_AN (
    P_ID IN NUMBER,
    P_TEN_MON IN NVARCHAR2,
    P_MO_TA IN NVARCHAR2,
    P_LOAI IN NVARCHAR2,
    P_TEN_ANH IN VARCHAR2
) IS
    L_BLOB BLOB;
    L_BFILE       BFILE;
    L_DEST_OFFSET INTEGER:=1;
    L_SRC_OFFSET  INTEGER:=1;
    L_LOBMAXSIZE  CONSTANT INTEGER := DBMS_LOB.LOBMAXSIZE;
BEGIN
    INSERT INTO MON_AN (
        ID,
        TEN_MON,
        MO_TA,
        LOAI,
        HINH_ANH
    ) VALUES (
        P_ID,
        P_TEN_MON,
        P_MO_TA,
        P_LOAI,
        EMPTY_BLOB()
    ) RETURN HINH_ANH INTO L_BLOB;
    L_BFILE := BFILENAME('DIRECT_OF_IMAGE', P_TEN_ANH);
    DBMS_LOB.FILEOPEN(L_BFILE, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADBLOBFROMFILE (L_BLOB, L_BFILE, L_LOBMAXSIZE, L_DEST_OFFSET, L_SRC_OFFSET);
    DBMS_LOB.FILECLOSE(L_BFILE);
    DBMS_OUTPUT.PUT_LINE('SIZE OF THE IMAGE IS: '
        || DBMS_LOB.GETLENGTH(L_BLOB));
    COMMIT;
END;