COMMIT;

DECLARE
    L_BLOB        BLOB;
    L_BFILE       BFILE;
    L_DEST_OFFSET INTEGER:=1;
    L_SRC_OFFSET  INTEGER:=1;
    L_LOBMAXSIZE  CONSTANT INTEGER := DBMS_LOB.LOBMAXSIZE;
BEGIN
    UPDATE MON_AN
    SET
        HINH_ANH = EMPTY_BLOB(
        )
    WHERE
        TEN_MON = 'Hamburger' RETURNING HINH_ANH INTO L_BLOB;
    L_BFILE := BFILENAME('DIRECT_OF_IMAGE', 'Hamburger.png');
    DBMS_LOB.FILEOPEN(L_BFILE, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADBLOBFROMFILE (L_BLOB, L_BFILE, L_LOBMAXSIZE, L_DEST_OFFSET, L_SRC_OFFSET);
    DBMS_LOB.FILECLOSE(L_BFILE);
    DBMS_OUTPUT.PUT_LINE('SIZE OF THE IMAGE IS: '
        || DBMS_LOB.GETLENGTH(L_BLOB));
    COMMIT;
END;
